---
# file: jenkinsci.yml
- hosts: jenkinsci
  remote_user: root
  tasks:
    - debug: msg="Creating a Jenkins pipeline job on {{ inventory_hostname }}"

    # - jenkins_job:
    #     name: Everything-as-code Pipeline
    #     config: "{{ lookup('file', 'templates/pipeline-job.xml') }}"
    #     url: "http://{{ inventory_hostname }}"
    #     user: admin
    #     password: admin
