apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: everything-as-code-image
  name: everything-as-code-image
spec:
  output:
    to:
      kind: ImageStreamTag
      name: everything-as-code:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM qaware-oss-docker-registry.bintray.io/base/alpine-k8s-openjdk8:8u121
      MAINTAINER M.-Leander Reimer <mario-leander.reimer@qaware.de>

      RUN mkdir -p /app
      ADD everything-as-code-1.2.3.tar /app

      WORKDIR /app/everything-as-code-1.2.3
      RUN chmod 755 bin/everything-as-code

      EXPOSE 18080

      CMD ./bin/everything-as-code
    binary:
      asFile: everything-as-code-1.2.3.tar
    type: Docker
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: alpine-k8s-openjdk8:8u121
    type: Docker
  triggers: {}